export const categorieData = [
  {
    img: "/images/big-mac-burger.png",
    title: "Big Mac Burger",
    slug: "/big-mac-burger",
    stars: 5,
    pastPrice: 15.99,
    newPrice: 10.0,
    time: 30,
  },
  {
    img: "/images/banana-pancakes.png",
    title: "Banana Pancakes",
    slug: "/banana-pancakes",
    stars: 4.9,
    pastPrice: 20.99,
    newPrice: 15.5,
    time: 25,
  },
  {
    img: "/images/fresh-farm-pizza.png",
    title: "Fresh Farm Pizza",
    slug: "/fresh-farm-pizza",
    stars: 4.5,
    pastPrice: 25.99,
    newPrice: 20.0,
    time: 30,
  },
  {
    img: "/images/grilled-sandwich.png",
    title: "Grilled Sandwich",
    slug: "/grilled-sandwich",
    stars: 4.3,
    pastPrice: 35.99,
    newPrice: 20.99,
    time: 35,
  },
  {
    img: "/images/taco-mexicana.png",
    title: "Taco Mexicana",
    slug: "/taco-mexicana",
    stars: 3.5,
    pastPrice: 40.99,
    newPrice: 20.5,
    time: 20,
  },
  {
    img: "/images/avacado-sandwich.png",
    title: "Avacado Sandwich",
    slug: "/avacado-sandwich",
    stars: 3,
    pastPrice: 15.99,
    newPrice: 10.0,
    time: 15,
  },
  {
    img: "/images/pasta-italiano.png",
    title: "Pasta Italiano",
    slug: "/pasta-italiano",
    stars: 2.5,
    pastPrice: 45.99,
    newPrice: 25.99,
    time: 10,
  },
  {
    img: "/images/shrimp-curry.png",
    title: "Shrimp Curry",
    slug: "/shrimp-curry",
    stars: 2.5,
    pastPrice: 19.99,
    newPrice: 10.99,
    time: 15,
  },
  {
    img: "/images/hot-dogs.png",
    title: "Hot dogs",
    slug: "/hot-dogs",
    stars: 2,
    pastPrice: 23.99,
    newPrice: 13.99,
    time: 10,
  },
  {
    img: "/images/sugary-donuts.png",
    title: "Sugary Donuts",
    slug: "/sugary-donuts",
    stars: 2,
    pastPrice: 45.99,
    newPrice: 25.9,
    time: 26,
  },
];
