export const data = [
  {
    _id: 0,
    slug: "/mindels-burger-and-fries",
    img: "/images/mindels-burger-and-fries.png",
    name: "Mindels Burger and Fries",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 1,
    slug: "/crison-sub-and-sandwiches",
    img: "/images/crison-sub-and-sandwiches.png",
    name: "Crison Sub and Sandwiches",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 2,
    slug: "/rolls-and-drools",
    img: "/images/rolls-and-drools.png",
    name: "Rolls and drools",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 3,
    slug: "/made-in-heaven",
    img: "/images/made-in-heaven.png",
    name: "Made in heaven",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 4,
    slug: "/italian-pizza",
    img: "/images/italian-pizza.png",
    name: "Italian pizza",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 5,
    slug: "/sandwich-home",
    img: "/images/sandwich-home.png",
    name: "Sandwich home",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 6,
    slug: "/mexican-green-wave",
    img: "/images/mexican-green-wave.png",
    name: "Mexican green wave",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 7,
    slug: "/italiono-restaurant",
    img: "/images/italiono-restaurant.png",
    name: "Italiono restaurant",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 8,
    slug: "/curry-trails",
    img: "/images/curry-trails.png",
    name: "Curry trails",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 9,
    slug: "/icing-donuts",
    img: "/images/icing-donuts.png",
    name: "Icing Donuts",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 10,
    slug: "/steak-and-greens",
    img: "/images/steak-and-greens.png",
    name: "Steak and greens",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 11,
    slug: "/healthy-and-tasty",
    img: "/images/healthy-and-tasty.png",
    name: "Healthy and tasty",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 12,
    slug: "/cheese-and-meat",
    img: "/images/cheese-and-meat.png",
    name: "Cheese and meat",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 13,
    slug: "/desert-on-plate",
    img: "/images/desert-on-plate.png",
    name: "Desert on plate",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 14,
    slug: "/fish-fiesta",
    img: "/images/fish-fiesta.png",
    name: "Fish Fiesta",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 15,
    slug: "/tibeatean-bites",
    img: "/images/tibeatean-bites.png",
    name: "Tibeatean bites",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 16,
    slug: "/urban-juice-cafe",
    img: "/images/urban-juice-cafe.png",
    name: "Urban juice cafe",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
  {
    _id: 17,
    slug: "/beakers-biryani",
    img: "/images/beakers-biryani.png",
    name: "Beakers Biryani",
    description: "$159 for two",
    star: 5,
    time: 30,
  },
];
