import { productType } from "../../../@types";
export const data: productType[] = [
  {
    _id: "0",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "1",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-1.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "2",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-2.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "3",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-3.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "4",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-4.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "5",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-5.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "6",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-6.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "7",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-7.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "8",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-8.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "9",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-9.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "1",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-10.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "1",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-11.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "1",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-12.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "1",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-13.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
  {
    _id: "1",
    slug: "/three-pepper-pizza",
    img: "/images/three-pepper-pizza-14.png",
    name: "Three Pepper Pizza",
    past_price: 67.99,
    new_price: 60,
    description: "Pizzalicious",
    star: 5,
    time: 30,
  },
];
